archives_base_name=rgbchat-neoforge
neoforge_version=21.11.45
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
neo_version_range=[21.11.0,)
loader_version_range=[3,)
mod_id=rgbchat
mod_name=RGB Chat
mod_license=MIT
maven_group=pageqwq.rgbchat
mod_version=1.0.2
org.gradle.daemon=false
org.gradle.debug=false
org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=/Library/Java/JavaVirtualMachines/liberica-jdk-25.jdk/Contents/Home