modLoader = "javafml"
loaderVersion = "[3.0,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/waterfrog68/RGB-Chat-Renewed/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "assets/rgbchat/icon.png"

description = '''RGB Chat: #RRGGBB colored and gradient text, client-side only.'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"